### ISSUE TITLE
000님이 생성한 프로그램에서 DB 연결이 잘되지 않습니다.  - 확인 부탁 드립니다. 

### ISSUE THREAD

**Issue by teamjangsong2022** [teamjangsong2022/Temp_Proj#5]
000님이 생성한 프로그램에서 DB 연결이 잘되지 않습니다.  - 확인 부탁 드립니다.

**Comment by daerikim2022** [comment]
해당 이슈는 담당자 확인이 필요한 이슈 입니다. 
확인후 다시 코멘트 달겠습니다.

**Comment by sawonlee2022** [comment]
제가 담장자 입니다. 해당 원인은 라이브러리 등록 이 안되어서 발생한 문제 입니다. 
문제는 모두 해결 완료 했습니다.

**Comment by sawonlee2022** [comment]
미션 완료
