### ISSUE TITLE
지금 프로잭트 중에 라이브러리 연결이 안되어서 개발에 어려움이 있습니다. 팀원들은 도와주세요. 

### ISSUE THREAD

**Issue by sawonlee2022** [teamjangsong2022/Temp_Proj#6]
지금 프로잭트 중에 라이브러리 연결이 안되어서 개발에 어려움이 있습니다. 팀원들은 도와주세요.

**Comment by daerikim2022** [comment]
JDBC 연결설정에 문제 가 있는것 같습니다. 

답변 

이렇게 해결해 보세요.

**Comment by sawonlee2022** [comment]
잘 마무리 되었습니다. 즐거운 하루 되세요.
